rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
bundler_args: --without integration
before_script:
  - bundle exec berks install
script:
  - bundle exec foodcritic -f any . --tags ~FC008 $SANDBOX/$COOKBOOK
  - bundle exec rubocop
